### ISSUE TITLE
Change Credit Card with Bitcoin Deposit

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#10]
Again, because we do not have credit card payments in the beginning could you please change the selected CARD message in the green text with the following? Attached a PSD from Claudiu.
![image](https://user-images.githubusercontent.com/32448630/32494293-b49c430e-c3c9-11e7-8bbe-10cc12d4b217.png)

**Comment by AlexandruAmugea** [comment]
I don't see where/if the psd is attached.

**Comment by MRazva** [comment]
it seems the upload do not support PSD - sent file on facebook

**Comment by MRazva** [comment]
sent on facebook

**Comment by AlexandruAmugea** [comment]
Partial fixed need bitcoin icon

**Comment by AlexandruAmugea** [comment]
Changed
