### ISSUE TITLE
Everything Stored locally 

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#11]
Because i have encountered a situation with: http://risk.fxrallyadministrator.com/clients-profit/ , from what alex told me it was done with bootstrap or something like that, and the providers deleted files or code or something, and the entire design was messy and ruined. Could we please have everything stored locally for Buroka in order to avoid such possible issues?

**Comment by AlexandruAmugea** [comment]
All the dependencies are installed and used for dev localy and for production they are all generated in a bundle.js file . The only resource is Bootstrap.css which will be also imported in the bundle.
