### ISSUE TITLE
in view desktop version on mobile

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#16]
![inked24140125_10211341028703585_1213182908_o_li](https://user-images.githubusercontent.com/32448630/33257003-35fad06c-d35d-11e7-83d9-bc1e0c98fa53.jpg)
![inked24139031_10211341028663584_495537485_o_li](https://user-images.githubusercontent.com/32448630/33257004-361711be-d35d-11e7-8e1d-db6db0b7ded7.jpg)
![inked24139951_10211341029863614_911128096_o_li](https://user-images.githubusercontent.com/32448630/33257005-363315f8-d35d-11e7-998c-e442b7ae1aa3.jpg)

some issues there with responsiveness

**Comment by AlexandruAmugea** [comment]
Please add resolutions that you've tested on .

**Comment by MRazva** [comment]
tested on Samsung S6 - from phone specs - 1440 x 2560 pixels, 16:9 ratio (~577 ppi density)

**Comment by MRazva** [comment]
but same situation happened on resizing the window on the laptop

**Comment by AlexandruAmugea** [comment]
Fixed
