### ISSUE TITLE
In mobile version

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#3]
In varianta de mobil sunt doua lucruri care sunt ciudatele.

1 textul asta nu este centrat
<img width="369" alt="capture" src="https://user-images.githubusercontent.com/32448630/31113872-1a7b9952-a824-11e7-8263-1eb44ecf956e.PNG">

2. inca apare vizibil textul de pe telefon (imaginea) 
<img width="373" alt="capture 2" src="https://user-images.githubusercontent.com/32448630/31113908-41689af6-a824-11e7-8209-a14d6c972fdd.PNG">

**Comment by AlexandruAmugea** [comment]
Fixed and pushed to Git. Please close issue if this was fixed.
