### ISSUE TITLE
Pop up at click on "Exchange"

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#4]
at the exchange form in the firs part of the website, when clicking on the "Exchange" button can we have a pop up like www.changelly.com does:
![image](https://user-images.githubusercontent.com/32448630/31115409-e1e2dc5c-a82a-11e7-9ad8-8ca0c2996abc.png)
Nothing much - identical with that one, but with our colors.

**Comment by AlexandruAmugea** [comment]
Ok i will add it
