### ISSUE TITLE
As seen in - section

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#5]
Hello, there is another thing to be done at the As seen in section:  
![image](https://user-images.githubusercontent.com/32448630/31115747-1e3dd87c-a82c-11e7-963d-d7eb55967d1b.png)
instead of having a picture maybe we can have logo-s with hover over effect and links to articles.

Bloomberg : https://www.bloomberg.com/news/articles/2016-12-21/who-owns-blockchain-goldman-bofa-amass-patents-for-coming-wars

Coindesk : https://www.coindesk.com/category/markets-news/markets-markets-news/markets-bitcoin/

The Guardian: https://www.theguardian.com/world/2016/aug/03/could-bitcoin-change-the-game-in-africa

BBC : http://www.bbc.com/news/business-31735976

Wall Street Journal: https://blogs.wsj.com/moneybeat/2014/07/17/south-africas-payfast-incorporates-bitcoin-as-payment-option/

The Economist: https://www.economist.com/blogs/baobab/2014/06/cash-transfers-africa

**Comment by MRazva** [comment]
![bloomberg](https://user-images.githubusercontent.com/32448630/31116195-d2de39a6-a82d-11e7-9288-cf10e2c3bea1.png)
![2000px-the_guardian svg](https://user-images.githubusercontent.com/32448630/31116191-d2d831c8-a82d-11e7-8f8c-9be198007abd.png)
![4b34c3c6-a1e4-4fa1-b045-fffed5a1c6f9](https://user-images.githubusercontent.com/32448630/31116190-d2d80040-a82d-11e7-8269-57fd31b0a16f.png)
![5842ab62a6515b1e0ad75b09](https://user-images.githubusercontent.com/32448630/31116194-d2dc104a-a82d-11e7-9f16-c57001e0b0eb.png)
![58482332cef1014c0b5e49be](https://user-images.githubusercontent.com/32448630/31116192-d2d9da3c-a82d-11e7-9d56-fec6398fd41f.png)
<img width="242" alt="1-oaulbynlm3mwv120gjgmjg" src="https://user-images.githubusercontent.com/32448630/31116193-d2db1e6a-a82d-11e7-8bad-01e0b8e6b32f.png">

**Comment by AlexandruAmugea** [comment]
I will modify the section.

**Comment by AlexandruAmugea** [comment]
Fixed and deployed.

**Comment by MRazva** [comment]
Putem sa le dam transparenta si sa incapa toate pe acelasi rand, apoi la hoverover sa apara culoarea normala? 

![image](https://user-images.githubusercontent.com/32448630/31121066-732df408-a83f-11e7-8c39-13e839b52f69.png)

**Comment by AlexandruAmugea** [comment]
Aveau deja greyscale dar unele erau deja alb negru, am adaugat opacitate, de asemenea a fost fixata si punerea pe doua linii
