### ISSUE TITLE
Mobile Format

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#6]
Hello, one more thing I could see on my Mobile (Samsung S6)

![feedback mobile version](https://user-images.githubusercontent.com/32448630/31119801-e3a66efe-a83a-11e7-8b0c-62298b4b83ec.jpg)

Can we have a little space between the number and the text in those boxes, and were is written about visa to have a centered format, it looks a bit off there.

**Comment by AlexandruAmugea** [comment]
Fixed and pushed to git.
