### ISSUE TITLE
Drop Down Form

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#7]
Hello, at the form drop down i have seen that the name doesn't match the icon:
![image](https://user-images.githubusercontent.com/32448630/31163868-343555c6-a8ed-11e7-9303-83423382e072.png)
E.g. - Bitcoin is BTC
USD has the BTC Icon

**Comment by AlexandruAmugea** [comment]
Only for testing, when the real data will be received every currency will be mapped corectly to the icon . We keep this open and to be solved when the real data will be received.
