### ISSUE TITLE
Buroka Logo

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#8]
We will need to add there a better quality logo.

**Comment by AlexandruAmugea** [comment]
Please attach the logo at high quality , from psd this was the best quality posibly.

**Comment by MRazva** [comment]
![buroka 1](https://user-images.githubusercontent.com/32448630/31167404-9a8498e8-a8fa-11e7-8519-b841c7c6a32a.png)

**Comment by AlexandruAmugea** [comment]
This is not the web logo, the web logo has Crypto Exchange white color also Buroka is transparent i will attach the logo from web. 
![logo](https://user-images.githubusercontent.com/7722118/31168589-88665a9e-a8fe-11e7-85b3-b39edd6aebf1.png)

**Comment by MRazva** [comment]
i hope this one is the good one
![buroka 2](https://user-images.githubusercontent.com/32448630/31169637-f5548c90-a901-11e7-9f74-675a0aa5182f.png)

**Comment by AlexandruAmugea** [comment]
Fixed and pushed

**Comment by MRazva** [comment]
great, much better, thanks
