### ISSUE TITLE
Hide Card Payments - since in the MVP we will not have it

### ISSUE THREAD

**Issue by MRazva** [AlexandruAmugea/baroka-lp#9]
Can you please hide this line, because in the MVP we will not have credit card payments.
![image](https://user-images.githubusercontent.com/32448630/32494197-65b788e8-c3c9-11e7-9e35-5ef871dedb0a.png)

**Comment by MRazva** [comment]
still to be solved - to be hidden

**Comment by AlexandruAmugea** [comment]
Solved
